name: Build And Release

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: ./NaMacro.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Install Inno Setup
        run: choco install innosetup --no-progress --yes

      - name: Run MAKE_SETUP
        run: installer\MAKE_SETUP.bat

      - name: Archive Installer
        uses: actions/upload-artifact@v3
        with:
          name: NaMacroJS-installer
          path: installer\output\NaMacroJS-setup.exe

  release:
    needs: build
    runs-on: windows-latest
    on: # release job의 on 설정 변경
      push:
        tags:
          - '*' # 모든 태그 푸시에 대해 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NaMacroJS-installer

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: NaMacroJS-setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }} # 태그 이름 사용
          tag: ${{ github.ref_name }} # 태그 이름 사용
          body: |
            Automatically generated release.
